// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiQnd7uRzmM5q724XjRBAAy4J3ke9eAg',
    appId: '1:756953631901:android:8cd8999506aeb156c05874',
    messagingSenderId: '756953631901',
    projectId: 'timetrackerv100',
    databaseURL: 'https://timetrackerv100-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timetrackerv100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBHhngEID_qmshGf6Cie8ov5K4SEDxL0',
    appId: '1:756953631901:ios:bbf3ffbd10bbec80c05874',
    messagingSenderId: '756953631901',
    projectId: 'timetrackerv100',
    databaseURL: 'https://timetrackerv100-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'timetrackerv100.firebasestorage.app',
    iosBundleId: 'com.example.test1',
  );
}
